[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"

[build]
  publish = ".vitepress/dist"
  command = "npx pnpm i --frozen-lockfile --store=node_modules/.pnpm-store && npm run build"

[[redirects]]
  from = "https://windicss.netlify.app/*"
  to = "https://windicss.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301
